In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,4,5],[7,8,9,10,11]])
b = np.array([4,5,6,7,8])

In [14]:
a-b

array([[-3, -3, -3, -3, -3],
       [ 3,  3,  3,  3,  3]])

In [10]:
a-2

array([-1,  0,  1,  2,  3])

In [1]:
a = [i+1 for i in range(10)]

In [4]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
!bash collectSubmission.sh

### Zipping file ###
### Creating PDFs ###
Created PDF knn.ipynb.
Created PDF svm.ipynb.
Created PDF softmax.ipynb.
Created PDF two_layer_net.ipynb.
Created PDF features.ipynb.
### Done! Please submit a1.zip and the pdfs to Gradescope. ###


In [9]:
np.sum(a, axis=0)

array([ 8, 10, 12, 14, 16])